chore: create ApplicationData folder if not exists
criticalmanufacturing/portal-sdk pull request #94
Opened 2024-11-21 10:11 UTC by joaoopereira

This PR solves the scenario (for now only seen in linux) when the ApplicationData folder doesn't exists:
![image](https://github.com/user-attachments/assets/34043946-ac4e-4901-90f5-8808d5ad9157)

before:
![image](https://github.com/user-attachments/assets/bda254c3-a0d6-46ee-9223-ccfac2c0204a)

after:
![image](https://github.com/user-attachments/assets/ac29595a-fe44-448b-bc50-f2df2b02871c)

2024-11-21 10:13 UTC, joaoopereira commented
I also want to porpose that all our references to FileSystem should be changed to IFileSystem, so we can use [System.IO.Abstractions](https://github.com/TestableIO/System.IO.Abstractions) to mock the filesystem and add more unit testing :)

2024-11-21 17:13 UTC, vitorpmoreira commented
> I also want to porpose that all our references to FileSystem should be changed to IFileSystem, so we can use [System.IO.Abstractions](https://github.com/TestableIO/System.IO.Abstractions) to mock the filesystem and add more unit testing :)

I'll open a WI for this. Thanks

2024-11-21 17:20 UTC, vitorpmoreira requested changes
Please version bump the portal-sdk, we don't have an automatic bump yet.
You just need to change the Version.props

2024-11-22 11:23 UTC, joaoopereira commented
> Please version bump the portal-sdk, we don't have an automatic bump yet. You just need to change the Version.props

done ✅

2024-11-22 11:43 UTC, vitorpmoreira approved these changes

2024-11-22 12:11 UTC, merged